# Can set testMode to property or assertion mode depending on how you want to test the system's properties
testMode: assertion
# You should ALWAYS set corpusDir to track coverage
corpusDir: corpus

# provide solc remappings to crytic-compile
cryticArgs:
  [
    "--solc-remaps",
    "@openzeppelin/contracts=lib/openzeppelin-contracts/contracts",
  ]
